name: 'Conventional Versioning'
description: 'Create Github Release using SemVer when pushing Conventional Comits'
author: ArwynFr
branding:
  icon: tag
  color: blue
inputs:
  pattern:
    description: 'Pattern of files to include in the release'
    required: false
  whatif:
    description: 'Set to "$true" if you want to calculate the next-version without creating the release'
    required: false
    default: '$false'
outputs:
  current-version:
    description: 'Current release version number found in the repository'
    value: ${{ steps.new-github-release.outputs.current-version }}
  bump-type:
    description: 'Type of version bump based on commit message'
    value: ${{ steps.new-github-release.outputs.bump-type }}
  next-version:
    description: 'Calculated target version of the new release'
    value: ${{ steps.new-github-release.outputs.next-version }}
runs:
  using: "composite"
  steps:

    - shell: pwsh
      id: new-github-release
      run: |
        "${{ github.token }}" | gh auth login --with-token
        & "$env:GITHUB_ACTION_PATH/functions/New-GithubRelease.ps1" `
          -RepositoryName "${{ github.repository }}" `
          -CommitMessage "${{ github.event.head_commit.message }}" `
          -Pattern "${{ inputs.pattern }}" `
          -Whatif:${{ inputs.whatif }}