= Conventional Versioning: new release
:toc: preamble

This Github action creates a new Github Release, using https://semver.org/[Semantic Versioning] and https://www.conventionalcommits.org/en/v1.0.0/[Conventional Commits].


== About

=== Versioning rules
See link:get-newVersion/README.adoc[get-newVersion] for details on versioning rules.

=== Release creation
This action uses https://cli.github.com/[Github CLI] and needs **not** to checkout the repository.
The release will autogenerate the notes, tag the source code, and include source archives to the release by default.
You can add additional files using the `pattern` input variable.
This pattern matches the syntax for https://cli.github.com/manual/gh_release_create[`gh release create`] command.

== Inputs

Pattern::
*Optional*. Files to include in the GitHub release.

Allow-additional-modifiers::
*Optional*. Set to `true` to support using additional modifiers `+` and `-` for minor and patch level updates respectively. Also supports using `NEW FEATURE:` footer for minor updates.
  
Feat-upgrades-minor::
*Optional*. Set to `false` to increment a patch bump instead of a minor one when the commit type is `feat:`.
  
Strict-types::
*Optional*. Set to `true` to fail this action when the commit type is not in the following list: `build`, `chore`, `ci`, `docs`, `feat`, `fix`, `perf`, `refactor`, `revert`, `style`, `test`.

== Outputs

Current-version::
Current version found in the repository, format `1.2.3`.

Bump-type::
Type of version bumping, one of the following: `major`, `minor`, `patch`.

Next-version::
Version number for the new release, format `1.2.3`.

## Example

This action will create a release with artifacts for each commit on the master branch :

```yml
on:
  push:
    branches: [main]

jobs:

  # insert another job that will build and upload some artifacts

  publish:
    runs-on: ubuntu-latest
    name: 'Publish a new release'
    steps:

    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: artifacts

    - uses: arwynfr/actions-conventional-versioning@v2
      with:
        pattern: artifacts/*
```

== Other actions
link:get-newVersion/README.adoc[get-newVersion]:: Calculates the new version number without creating a Release. Usefull before build if you want to embed the new version number in the sources. This action replaces obsolete `whatif` input parameter.
link:new-versionTags/README.adoc[new-versionTags]:: Adds major (`v1`) and minor (`v1.2`) tags to the repository. Usefull with GitHub actions, or any situation when you want to allow other repositories to reference the "latest" version of a given major or minor version.
