= Conventional Versioning: new release
:toc: preamble

This Github action creates a new Github Release, using https://semver.org/[Semantic Versioning] and https://www.conventionalcommits.org/[Conventional Commits] messages.

== About
=== Current version
The current version is based on latest Github Release *tag name*.
If there is no release or the tag is not a valid version number, the action will default to `0.0.0`.
Current version should not include any prefix.
Values such as `v1.2.3` or `ver-1.2.3` are **not** understood and will default to `0.0.0`.

=== Change type
The type of version change is based on HEAD commit message, taken from https://docs.github.com/en/actions/learn-github-actions/contexts[`github.event` context]:

* `Fix` will bump the patch version
* `Feature` will bump the minor version
* `Breaking` will bump major version

Breaking changes can either use the explicit notation (`BREAKING CHANGE:` in the body or footer) or the bang notation (`type(scope)!: description` in the first line).
Feature must use the `feat` type value.
If the message is not understood as a valid conventional commit, the change type will default to `Fix`.
You should consider using this action in conjunction with another one enforcing commit message format.

=== Release creation
This action uses https://cli.github.com/[Github CLI] and needs **not** to checkout the repository.
The release will autogenerate the notes, tag the source code, and include source archives to the release by default.
You can add additional files using the `pattern` input variable:

* Version `v0` matches the syntax for https://cli.github.com/manual/gh_release_create[`gh release create`] command and does not expand wildcards
* Version `v1` will expand wildcards so you can use patterns such as `*.zip`

== Inputs
Pattern::
Wildcard pattern used to add files in the release.

== Outputs
Current-version::
Current version found in the repository, format `1.2.3`.

Bump-type::
Type of version bumping, one of the following: `Breaking`, `Feature`, `Fix`.

Next-version::
Version number for the new release, format `1.2.3`.

## Example

This action will create a release with artifacts for each commit on the master branch :

```yml
on:
  push:
    branches: [master]

jobs:

  # insert another job that will build and upload some artifacts

  publish:
    runs-on: ubuntu-latest
    name: 'Publish a new release'
    steps:

    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: artifacts

    - uses: arwynfr/actions-conventional-versioning@v1
      with:
        pattern: artifacts/*
```

== Other actions
link:get-newVersion/README.adoc[get-newVersion]:: Calculates the new version number without creating a Release. Usefull before build if you want to embed the new version number in the sources. This action replaces obsolete `whatif` input parameter.
link:new-versionTags/README.adoc[new-versionTags]:: Adds major (`v1`) and minor (`v1.2`) tags to the repository. Usefull with GitHub actions, or any situation when you want to allow other repositories to reference the "latest" version of a given major or minor version.
