name: 'Conventional Versioning: get new version'
description: 'Provides the new SemVer version based on Conventional Comits'
author: ArwynFr
branding:
  icon: tag
  color: blue

outputs:

  current-version:
    description: 'Current release version number found in the repository'
    value: ${{ steps.new-github-release.outputs.current-version }}

  bump-type:
    description: 'Type of version bump based on commit message'
    value: ${{ steps.new-github-release.outputs.bump-type }}

  next-version:
    description: 'Calculated target version of the new release'
    value: ${{ steps.new-github-release.outputs.next-version }}

runs:
  using: "composite"
  steps:

    - shell: pwsh
      id: new-github-release
      run: |
        "${{ github.token }}" | gh auth login --with-token
        & "${env:GITHUB_ACTION_PATH}/functions/New-GithubRelease.ps1" `
          -RepositoryName "${{ github.repository }}" `
          -CommitMessage "${{ github.event.head_commit.message }}" `
          -Whatif