= Conventional Versioning: get-newVersion
:toc: preamble

This Github action creates a new Github Release, using https://semver.org/[Semantic Versioning] and https://www.conventionalcommits.org/en/v1.0.0/[Conventional Commits].

== About
=== Current version
The current version is based on latest Github Release *tag name*.
If there is no release or the tag is not a valid version number, the action will default to `0.1.0`. Current version should not include any prefix, values such as `v1.2.3` or `ver-1.2.3` are **not** understood by this action and will have the action use default value of `0.1.0`.

=== Change type
The type of version change is based on HEAD commit message, taken from https://docs.github.com/en/actions/learn-github-actions/contexts[`github.event` context]. The commit message is expected to follow the format specified in the conventional commits specifications:

* Using the `!` modifier or the `BREAKING CHANGE:` footer will increment a major version
* Using the `feat:` commit typ will increment a minor version
* Other commits will increment a patch version

== Inputs

Allow-additional-modifiers::
*Optional*. Set to `true` to support using additional modifiers `+` and `-` for minor and patch level updates respectively. Also supports using `NEW FEATURE:` footer for minor updates.
  
Feat-upgrades-minor::
*Optional*. Set to `false` to increment a patch bump instead of a minor one when the commit type is `feat:`.
  
Strict-types::
*Optional*. Set to `true` to fail this action when the commit type is not in the following list: `build`, `chore`, `ci`, `docs`, `feat`, `fix`, `perf`, `refactor`, `revert`, `style`, `test`.

== Outputs
Current-version::
Current version found in the repository, format `1.2.3`.

Bump-type::
Type of version bumping, one of the following: `major`, `minor`, `patch`.

Next-version::
Version number for the new release, format `1.2.3`.

## Example

This action will create a release with artifacts for each commit on the master branch :

```yml
on:
  push:
    branches: [main]

jobs:

  publish:
    runs-on: ubuntu-latest
    name: 'Compute new version'
    steps:

    - uses: arwynfr/actions-conventional-versioning/get-newVersion@v2
      id: next-version
      with:
        allow-additional-modifiers: 'true'
        feat-upgrades-minor: 'false'
        strict-types: 'true'

    - run: echo ${{ steps.next-version.output.next-version }}

    - run: echo ${{ steps.next-version.output.bump-type }}
      
```
