= Conventional Versioning: get new version
:toc: preamble

This Github action calculates a new product version, using https://semver.org/[Semantic Versioning] and https://www.conventionalcommits.org/[Conventional Commits] messages.

== About
=== Current version
The current version is based on latest Github Release *tag name*.
If there is no release or the tag is not a valid version number, the action will default to `0.0.0`. Current version should not include any prefix, values such as `v1.2.3` or `ver-1.2.3` are **not** understood by this action and will have the action use default value of `0.0.0`.

=== Change type
The type of version change is based on HEAD commit message, taken from https://docs.github.com/en/actions/learn-github-actions/contexts[`github.event` context]:

* `Fix` will bump the patch version
* `Feature` will bump the minor version
* `Breaking` will bump major version

Breaking changes can either use the explicit notation (`BREAKING CHANGE:` in the body or footer) or the bang notation (`type(scope)!: description` in the first line).
Feature must use the `feat` type value.
If the message is not understood as a valid conventional commit, the change type will default to `Fix`.
You should consider using this action in conjunction with another one enforcing commit message format.

=== Release creation
This action uses https://cli.github.com/[Github CLI] and needs **not** to checkout the repository.
The release will autogenerate the notes, tag the source code, and include source archives to the release by default.
You can add additional files using the `pattern` input variable.
This pattern matches the syntax for https://cli.github.com/manual/gh_release_create[`gh release create`] command.

== Inputs
_None_

== Outputs
Current-version::
Current version found in the repository, format `1.2.3`.

Bump-type::
Type of version bumping, one of the following: `Breaking`, `Feature`, `Fix`.

Next-version::
Version number for the new release, format `1.2.3`.

## Example

This action will create a release with artifacts for each commit on the master branch :

```yml
on:
  push:
    branches: [master]

jobs:

  publish:
    runs-on: ubuntu-latest
    name: 'Compute new version'
    steps:

    - uses: arwynfr/actions-conventional-versioning/get-newVersion@1.0.0
      id: next-version

    - run: echo ${{ steps.next-version.output.next-version }}

    - run: echo ${{ steps.next-version.output.bump-type }}
      
```
