name: version

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  version:
    runs-on: ubuntu-latest
    name: 'Add major and minor version tags'
    steps:
      - name: Create version tags
        uses: arwynfr/actions-conventional-versioning/new-versionTags@master
